### ISSUE TITLE
Pinterest script loaded only on the first page

### ISSUE THREAD

**Issue by sagar7993** [robinmetral/gatsby-plugin-pinterest#2]
This plugin uses `onClientEntry` gatsby hook, which runs only the first time gatsby page loads in the browser. If you're trying to use this plugin on a website with multiple pages, then the pin it button will only appear on the images on the first page you visit. Consider using `onRouteUpdate` instead of  `onClientEntry` in the gatsby-browser.js file to inject the Pinterest script. You'd also have to ensure that you're only loading the Pinterest script just once in the head section of the document.

**Comment by robinmetral** [comment]
Hi @sagar7993, thanks for raising the issue! Sorry for my late reply, I was away for the last couple of weeks.
I'll look into this ASAP 🙂 Let me know if you have any other comments/suggestions for the plugin!

**Comment by robinmetral** [comment]
@sagar7993 actually, would you like to make a PR? :slightly_smiling_face:

**Comment by sagar7993** [comment]
@robinmetral never mind, looks like this wasn't an issue. Seems to work just fine now. Closing this issue.
