### ISSUE TITLE
Save Button only loads on page refresh for manually set `data-pin-do` tags

### ISSUE THREAD

**Issue by robinske** [robinmetral/gatsby-plugin-pinterest#28]
- `gatsby-plugin-pinterest` version: 3.2.2

Problem description:

Save Button does not appear until page refresh if you _don't_ include the `saveButton` attribute in the plugin options (which sets `data-pin-hover`) and instead include a [tag](https://developers.pinterest.com/docs/widgets/save/?) where you want the pin it button to appear like so (which adds the save button for individual images):
```
<a href="https://www.pinterest.com/pin/create/button/" data-pin-do="buttonBookmark">
</a>
```

Suggested solution:
PR incoming

I can create a small reproduction if needed but wanted to submit the issue while it was fresh in my mind.

**Comment by robinmetral** [comment]
Thanks for bringing this up @robinske! I think this makes total sense and it's probably a common use case. Let's follow up on the PR 🙂
