### ISSUE TITLE
Add ability to set data attributes on gatsby-image img tags to support pin type and source settings

### ISSUE THREAD

**Issue by robinske** [robinmetral/gatsby-plugin-pinterest#30]
According to [the docs](https://developers.pinterest.com/docs/widgets/save/?#button-style-settings) you can set attributes like `data-pin-media` or `data-pin-url` or `data-pin-nopin` "individually to images on your page." 

However gatsby-image [doesn't support setting attributes on the img tag](https://github.com/gatsbyjs/gatsby/issues/24159) so something like this won't work:

```javascript
<Img
  fluid={image}
  data-pin-url="https://mysite.com/images/dinner-rolls.png" // ignored
/>
```

This prevents setting attributes when `data-pin-hover` is set to true or setting `data-pin-nopin` to ignore images on the page when any image (`buttonBookmark`) is set. 

There's probably a workaround for this but I don't know one off the top of my head. Documenting it here for reference.

**Comment by robinske** [comment]
This might be solved by the new gatsby image plugin - I'll test this out soon https://github.com/gatsbyjs/gatsby/discussions/27950

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
