### ISSUE TITLE
Don't show bookmark button by default

### ISSUE THREAD

**Issue by MichaelDeBoey** [robinmetral/gatsby-plugin-pinterest#4]
@robinmetral After @osiux's PR to change the inject method (#3) and your comment (https://github.com/robinmetral/gatsby-plugin-pinterest/pull/3#issuecomment-592023968), I found out that the plugin automatically add the bookmark button on each image you have on your gatsby site.

I'd like to have this default changed, so users of [`gatsby-remark-embedder`](https://github.com/MichaelDeBoey/gatsby-remark-embedder/) won't have this side-effect if they just want to include an embedded board/pin/profile.
Then it's an opt-in for users who want to have this behaviour.

Of course this is for when @osiux's https://github.com/MichaelDeBoey/gatsby-remark-embedder/pull/73 is merged, as `gatsby-remark-embedder` doesn't support Pinterest at this moment.

**Comment by robinmetral** [comment]
Agreed! I think more options for users would be great. This is only the Pinterest script's default behavior.

Do you want to look into how to disable this by default?

I can help out if needed.

**Comment by MichaelDeBoey** [comment]
Basically when that one's merged, I want people to just do the following by default:

```js
plugins: [
  {
    resolve: `gatsby-transformer-remark`,
    options: {
      plugins: [
        `gatsby-remark-embedder`,
      ],
    },
  },
  `gatsby-plugin-pinterest`,
];
```
So it's in line with how they would do it when using [`gatsby-plugin-twitter`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-twitter) or [`gatsby-plugin-instagram-embed`](https://github.com/jlengstorf/gatsby-plugin-instagram-embed)

**Comment by MichaelDeBoey** [comment]
On a first look at [the _pinit_ docs](https://developers.pinterest.com/tools/widget-builder/?type=pinit&buttonType=imageHover), I think only running this line on the opt-in would make it work:
https://github.com/robinmetral/gatsby-plugin-pinterest/blob/2279a06804807077c14cc3f819754535090d29ed/gatsby-browser.js#L7

**Comment by MichaelDeBoey** [comment]
I'll create a PR later today to check it out 🙂

**Comment by osiux** [comment]
@MichaelDeBoey sorry if you were working on it! Didn't saw the comment before and created a PR for this.
