### ISSUE TITLE
gatsby-plugin-pinterest is not working for latest Gatsby. 

### ISSUE THREAD

**Issue by dev1980** [robinmetral/gatsby-plugin-pinterest#54]
Invalid plugin options for "gatsby-plugin-pinterest":

- 'round' is no longer supported. Use 'saveButton.round' instead by setting it to the same value you had before on 'round'.
- 'tall' is no longer supported. Use 'saveButton.tall' instead by setting it to the same value you had before on  
'tall'.

not finished open and validate gatsby-configs, load plugins - 0.612s

I am trying to add gatsby-plugin-pinterest to the gatsby-shopify -starter project.

- `gatsby-plugin-pinterest` version:
- `node` version:
- `npm` version:

Relevant code or config

```javascript

```

What you did:

What happened:

Reproduction repository:

Problem description:

Suggested solution:

**Comment by robinmetral** [comment]
Hi @dev1980, did you try to do what the plugin suggests?

> - 'round' is no longer supported. Use 'saveButton.round' instead by setting it to the same value you had before on 'round'.
> - 'tall' is no longer supported. Use 'saveButton.tall' instead by setting it to the same value you had before on
'tall'.

If that doesn't fix it, I'll need to know more. In that case, please edit your issue using the issue template (answer the questions that you see at the bottom of your report).

**Comment by robinmetral** [comment]
Closing as stale 🙂 Please comment in case this is still relevant!
